import {
  Accordion,
  Badge,
  Button,
  Card,
  NumberInput,
  Paper,
  Textarea,
  TextInput,
  createTheme,
} from "@mantine/core";

export const brandTheme = createTheme({
  primaryColor: "brandBlue",
  primaryShade: { light: 5, dark: 4 },
  defaultRadius: "lg",
  fontFamily: '"Golos Text", system-ui, sans-serif',
  fontFamilyMonospace: '"JetBrains Mono", monospace',
  headings: {
    fontFamily: 'Unbounded, "Golos Text", sans-serif',
    fontWeight: "700",
    sizes: {
      h1: { fontSize: "clamp(1.75rem, 5vw, 3rem)", lineHeight: "1.08" },
      h2: { fontSize: "clamp(1.2rem, 3vw, 1.75rem)", lineHeight: "1.16" },
      h3: { fontSize: "1.05rem", lineHeight: "1.25" },
    },
  },
  colors: {
    brandBlue: [
      "#f0f7ff",
      "#e1efff",
      "#c7e2ff",
      "#9dccff",
      "#64aeff",
      "#2e90ff",
      "#197be5",
      "#1165be",
      "#0f5198",
      "#123f73",
    ],
    brandNavy: [
      "#eef3f9",
      "#d8e2ef",
      "#b3c5dc",
      "#86a2c3",
      "#5e82aa",
      "#3f6793",
      "#2c507b",
      "#19355f",
      "#132b4f",
      "#0d213e",
    ],
    brandSand: [
      "#fdfbf7",
      "#faf7f1",
      "#f6f2ea",
      "#f1ece3",
      "#e9e1d5",
      "#ddd2c1",
      "#cbbba4",
      "#ae987b",
      "#8b7458",
      "#6d5943",
    ],
    brandYellow: [
      "#fffbea",
      "#fff5c7",
      "#ffeb8a",
      "#ffdf57",
      "#ffd23f",
      "#f5b700",
      "#d89500",
      "#b57400",
      "#925a00",
      "#754600",
    ],
    brandCyan: [
      "#e8fbff",
      "#cef5fc",
      "#9ee8f4",
      "#65d6e9",
      "#2bc1dc",
      "#0aadcb",
      "#0792ad",
      "#08778e",
      "#0a6073",
      "#0b4e5e",
    ],
    brandGreen: [
      "#eefcf3",
      "#d5f7e1",
      "#a9edc3",
      "#78e0a2",
      "#4dd184",
      "#22b866",
      "#189951",
      "#127a40",
      "#0f6033",
      "#0b4a28",
    ],
  },
  components: {
    Button: Button.extend({ defaultProps: { radius: "xl", fw: 600 } }),
    Badge: Badge.extend({ defaultProps: { radius: "xl", variant: "light" } }),
    Card: Card.extend({ defaultProps: { radius: "xl", padding: "lg" } }),
    Paper: Paper.extend({ defaultProps: { radius: "xl" } }),
    Accordion: Accordion.extend({ defaultProps: { radius: "lg" } }),
    TextInput: TextInput.extend({ defaultProps: { radius: "md" } }),
    Textarea: Textarea.extend({ defaultProps: { radius: "md" } }),
    NumberInput: NumberInput.extend({ defaultProps: { radius: "md" } }),
  },
});
