"""Import all models so SQLAlchemy and Alembic discover their metadata."""

from app.interviews.intelligence_models import (
    IntelligenceAIAdmission,
    IntelligenceAIUsage,
    IntelligenceAnswer,
    IntelligenceAnswerReview,
    IntelligenceAssessment,
    IntelligenceAttemptStage,
    IntelligenceAttemptStatus,
    IntelligenceDifficulty,
    IntelligenceInterview,
    IntelligenceInterviewType,
    IntelligenceMentorComment,
    IntelligenceProcessingAttempt,
    IntelligenceProcessingStatus,
    IntelligenceQuestion,
    IntelligenceQuestionKind,
    IntelligenceQuestionModerationStatus,
    IntelligenceReviewSource,
    IntelligenceReviewStatus,
    IntelligenceSpeaker,
    IntelligenceSpeakerRole,
    IntelligenceTranscriptionUsage,
    IntelligenceUtterance,
)
from app.interviews.models import (
    Company,
    CompanyAlias,
    InterviewCard,
    InterviewCardFrequency,
    InterviewCardOccurrence,
    InterviewCardProgress,
    InterviewDeck,
    InterviewProcess,
    InterviewProcessStage,
    InterviewProcessStageAttachment,
    InterviewProcessStatus,
    InterviewReviewRating,
    InterviewStageComment,
    InterviewStageType,
    InterviewTopicSelection,
)
from app.knowledge.models import (
    KnowledgeEntry,
    KnowledgeEntryKind,
    KnowledgeTopic,
    KnowledgeTopicTrack,
)
from app.mentors.models import (
    MentorDocumentKind,
    MentorStudent,
    MentorStudentDocument,
    MentorStudentNote,
    MentorTrackAssignment,
    MockInterview,
    MockInterviewStatus,
    StudentLearningStatus,
    StudentStrengthLevel,
)
from app.progress.models import ProgressStatus, TopicProgress
from app.roadmaps.models import Roadmap, RoadmapEnrollment, RoadmapSection, Topic
from app.tracks.models import LearningTrack, LearningTrackEnrollment, LearningTrackRoadmap
from app.users.models import User, UserRole

__all__ = [
    "Company",
    "CompanyAlias",
    "MentorStudent",
    "MentorTrackAssignment",
    "MentorStudentDocument",
    "MentorStudentNote",
    "MentorDocumentKind",
    "MockInterview",
    "MockInterviewStatus",
    "StudentLearningStatus",
    "StudentStrengthLevel",
    "KnowledgeEntry",
    "KnowledgeEntryKind",
    "KnowledgeTopic",
    "KnowledgeTopicTrack",
    "InterviewCard",
    "InterviewCardOccurrence",
    "InterviewCardFrequency",
    "InterviewCardProgress",
    "InterviewDeck",
    "InterviewProcess",
    "InterviewProcessStage",
    "InterviewProcessStageAttachment",
    "InterviewProcessStatus",
    "InterviewReviewRating",
    "InterviewStageType",
    "InterviewStageComment",
    "InterviewTopicSelection",
    "IntelligenceAIUsage",
    "IntelligenceAIAdmission",
    "IntelligenceAnswer",
    "IntelligenceAnswerReview",
    "IntelligenceAssessment",
    "IntelligenceAttemptStage",
    "IntelligenceAttemptStatus",
    "IntelligenceDifficulty",
    "IntelligenceInterview",
    "IntelligenceInterviewType",
    "IntelligenceMentorComment",
    "IntelligenceProcessingAttempt",
    "IntelligenceProcessingStatus",
    "IntelligenceQuestion",
    "IntelligenceQuestionKind",
    "IntelligenceQuestionModerationStatus",
    "IntelligenceReviewSource",
    "IntelligenceReviewStatus",
    "IntelligenceSpeaker",
    "IntelligenceSpeakerRole",
    "IntelligenceTranscriptionUsage",
    "IntelligenceUtterance",
    "LearningTrack",
    "LearningTrackEnrollment",
    "LearningTrackRoadmap",
    "ProgressStatus",
    "Roadmap",
    "RoadmapEnrollment",
    "RoadmapSection",
    "Topic",
    "TopicProgress",
    "User",
    "UserRole",
]
